### ISSUE TITLE
已修复：要一直Swipe才会有显示出菜单？滑动不够灵敏。

### ISSUE THREAD

**Issue by tangchao0106** [yanzhenjie/SwipeRecyclerView#1]
这个体验不好,要拖着才会有,幅度还要大才有反应

**Comment by yanzhenjie** [comment]
因为今天刚发布，稍微有点问题：  
1. 滑动时如果手指上下抖动时会取消滑动菜单。  
2. 滑动不是很灵敏，需要手指一直按着，没有惯性。  
感谢广大的网友测试并回馈缺点，现已全部优化修复，大家可以下载更新使用了。希望大家以后多多支持我的创作，再次感谢。

**Comment by tangchao0106** [comment]
大神.牛,继续优化

**Comment by zxyaust** [comment]
其实这个问题还是没有解决的太好,应该给一个滑动的难易程度,现在还是有时候划出来是很困难,我记得viewdaghelper里面有一个调节的参数,这里希望也有吧

**Comment by yanzhenjie** [comment]
@zxyaust   好的，此问题已收录，马上优化。
