### ISSUE TITLE
滑动的时候可以隐藏item中某个view吗？

### ISSUE THREAD

**Issue by JakeWoki** [yanzhenjie/SwipeRecyclerView#10]
[RecyclerViewEnhanced](https://github.com/nikhilpanju/RecyclerViewEnhanced)
类似这个的功能，不过这个项目滑动和SwipeRefreshLayout冲突，希望可以增加

**Comment by yanzhenjie** [comment]
滑动的时候隐藏某个View？这个不太明白你的意思哦。
我项目和SwipeRefreshLayout不冲突的，demo有例子演示的。

**Comment by JakeWoki** [comment]
滑动时隐藏item中某个view，效果如下图中的button
https://github.com/nikhilpanju/RecyclerViewEnhanced/raw/master/sample/src/common/images/Demo.gif

**Comment by yanzhenjie** [comment]
暂不支持，今天会更新一个版本，你说的这个功能会做支持。感谢反馈。
