### ISSUE TITLE
item删除条目复用错误

### ISSUE THREAD

**Issue by w296365959** [yanzhenjie/SwipeRecyclerView#102]
使用默认的侧滑删除，当划出一个条目，点击删除该条目，然后点击附近可见的一个条目触发item点击事件，跳转到其他页面，然后再返回，下面加载出来的item，会出现没有关闭侧滑的

**Comment by ggoyea** [comment]
是的，这个问题比较严重，暂时找不到解决办法。

**Comment by yanzhenjie** [comment]
点击Item菜单时，必须先关闭menu，demo中也有列子的。

**Comment by w296365959** [comment]
点击menu时有提供关闭menu的方法么？
而且我这点击menu是直接删除该条目( ⊙ o ⊙ )啊！

**Comment by yanzhenjie** [comment]
```java
menuBridge.closeMenu();
```
