### ISSUE TITLE
提个删除功能意见

### ISSUE THREAD

**Issue by Sum-sdl** [yanzhenjie/SwipeRecyclerView#103]
希望能加一个控制开关来控制某一个项隐藏删除功能，其他项不影响删除功能。
把final去掉，方便用户自己重新添加一些东西哦。

**Comment by yanzhenjie** [comment]
没有太看明白是什么意思。

**Comment by Sum-sdl** [comment]
比如RecyclerView的第一项，不需要侧滑删除功能，即第一项不能侧滑，其他项正常能侧滑哦

**Comment by yanzhenjie** [comment]
这个功能本身就是有的。
