### ISSUE TITLE
可以通过编写xml实现SwipeMenuItem的布局吗？

### ISSUE THREAD

**Issue by kaikaifly** [yanzhenjie/SwipeRecyclerView#107]

**Comment by yanzhenjie** [comment]
可以，参考自定义的Activity。

**Comment by cdcdec** [comment]
可以更新SwipeMenuItem的布局吗？  就是有两个菜单  一个是"添加"  一个是"删除"，根据后台的数据 显示"添加"或者"删除"，同时只显示一个。当点击"添加"  请求后台接口 ，显示"删除"；当点击"删除"  请求后台接口 ，显示"添加"；

**Comment by yanzhenjie** [comment]
@cdcdec 可以，更新当前item或者所有item，在MenuCreator中根据数据重新创建菜单即可。
