### ISSUE TITLE
引入报错

### ISSUE THREAD

**Issue by aikongmeng** [yanzhenjie/SwipeRecyclerView#113]
Error:Execution failed for task ':cehua:processDebugManifest'.
> Manifest merger failed : Attribute meta-data#android.support.VERSION@value value=(26.0.0-alpha1) from [com.android.support:appcompat-v7:26.0.0-alpha1] AndroidManifest.xml:27:9-38
  	is also present at [com.android.support:recyclerview-v7:25.3.1] AndroidManifest.xml:24:9-31 value=(25.3.1).
  	Suggestion: add 'tools:replace="android:value"' to <meta-data> element at AndroidManifest.xml:25:5-27:41 to override.

**Comment by yanzhenjie** [comment]
理论上这种issue是直接关闭的，上面已经说了解决办法了，类似问题只要在manifest中重写冲突属性即可。
