### ISSUE TITLE
item会出现间隔

### ISSUE THREAD

**Issue by sieml** [yanzhenjie/SwipeRecyclerView#120]
我把item的高度设置成40dp或者更小时, 这个时候出现了item之间的间距, 请问如何处理? 比较急..

**Comment by yanzhenjie** [comment]
我刚才测试了`40dp`、`20dp`，并没有出现你说的问题，理论上也不会出现这个问题，所以应该不是[SwipeRecyclerView](https://github.com/yanzhenjie/SwipeRecyclerView)的问题。  
你可以检查你的`ItemView`的的`padding`、`ItemDecoration`、其它逻辑等。

**Comment by sieml** [comment]
额, 没设置过任何padding和itemDecoration

**Comment by yanzhenjie** [comment]
我和几个小伙伴测试没有出现，你用我demo跑一下看看。

**Comment by sieml** [comment]
int width = getResources().getDimensionPixelSize(R.dimen.item_height);//60dp
     int height = ViewGroup.LayoutParams.MATCH_PARENT;

     实例化SwipeMenuCreator 我创建了两个菜单, 用的上面的宽高.

**Comment by yanzhenjie** [comment]
[SwipeRecyclerView](https://github.com/yanzhenjie/SwipeRecyclerView)是哪个版本的？

**Comment by sieml** [comment]
忘记了, 我当时是导入代码的
