### ISSUE TITLE
SwipeMenuRecyclerView图片拖拽只能放在相邻的位置？

### ISSUE THREAD

**Issue by Doraemonhub** [yanzhenjie/SwipeRecyclerView#121]
您好，在使用拖拽的时候发现只能放在相邻的位置，长按拖拽到达相邻的位置之后，就自己放在那个位置了，请问怎么解决？

**Comment by yanzhenjie** [comment]
手指用的力小了吧？拖拽的时候不能太拉风，太拉风了我也没办法。这个拖拽是`RecyclerView`自带的一个功能，没法通过改`SwipeRecyclerView`源码优化呢。

**Comment by Doraemonhub** [comment]
后来自己发现是拖拽后触发监听，然后程序抛异常了，已解决
