### ISSUE TITLE
俩个SwipeMenuRecyclerView不能嵌套吗

### ISSUE THREAD

**Issue by tracybai7989** [yanzhenjie/SwipeRecyclerView#122]
俩个SwipeMenuRecyclerView不能嵌套吗

**Comment by yanzhenjie** [comment]
我没有嵌套过，理论上应该会有冲突。如果是`Item`出现多个`SubItem`，而`SubItem`需要侧滑删除，建议不要嵌套`SwipeRecyclerView`，直接在Item中使用`LinarLayout#addView(View)`，因为子Item已经不需要重用了。被动态添加进去的`View`可以用`SwipeMenuLayout`做侧滑菜单，具体参考Demo自定义`menu`。
不过值得注意的是，每个`Item`被创建后应该`LinarLayout#removeAllViews()`移除子`View`后再添加子`View`。

**Comment by tracybai7989** [comment]
嗯嗯，嵌套一直显示已经设置过Adapter 了。 我试试你说的这种做。 谢谢
