### ISSUE TITLE
我想在指定的item里面显示侧滑删除功能

### ISSUE THREAD

**Issue by Chenshuai770** [yanzhenjie/SwipeRecyclerView#126]
我的应用里面有个功能,比如列表有10个,我只想在前三个里面可以显示侧滑删除添加功能,后面几个item里面不出现,请问如何实现

**Comment by yanzhenjie** [comment]
ViewType.

**Comment by Chenshuai770** [comment]
大神,请你说的具体一点,我目前找不到你说的ViewType这个,只找到了mRlvProStateList.getItemViewType()这个,非常感谢

**Comment by yanzhenjie** [comment]
就是Adapter的ViewType，Demo中有示例的。
