### ISSUE TITLE
SwipeMenuItem字体大小设置问题

### ISSUE THREAD

**Issue by artisan-android** [yanzhenjie/SwipeRecyclerView#139]
您好！关于SwipeMenuItem中
`    public SwipeMenuItem setTextSize(@Px int titleSize) {
        this.titleSize = titleSize;
        return this;
    }`
这个描述是否是说这个titleSize参数设置是像素呢？如果是的话那么这个描述有错误。
因为我在查看SwipeMenuView代码时。您是直接设置
`textView.setTextSize(textSize);`
如果是这样的话，请您查看一下TextView该函数描述，其实是sp格式，然后textview自动帮转换为px的
所以SwipeMenuItem 中setTextSize函数应该设置的sp值而不是px，误导了使用者

**Comment by yanzhenjie** [comment]
确认有这个问题，我把`@Px`注解去掉。这是一个重复的问题，这里继续回复：#134 。
