### ISSUE TITLE
SwipeMenuLayout 没有滑出和关闭的监听

### ISSUE THREAD

**Issue by fangshuai0119** [yanzhenjie/SwipeRecyclerView#14]

**Comment by yanzhenjie** [comment]
是侧滑菜单吗？监听滑出和关闭需要做什么呢？看看在现在的基础上能否直接实现。

**Comment by fangshuai0119** [comment]
我是打算加在RecyclerView 的item中的，不想直接使用您封装好的SwipeRecyclerView，因为如果使用您封装的，对我这边的改动太大，代码侵入性太强，所以就想自己实现，当listView 中的一行滑出的时候，其余行隐藏的效果

**Comment by yanzhenjie** [comment]
1. 就是和原生的RecyclerView一样的使用方法，代码侵入性太强这个说法可能还需斟酌。
2. 如果你要用在ListView中，需要你自己封装那些，我的SwipeRecyclerView是支持滑出一个时隐藏其它的。

**Comment by fangshuai0119** [comment]
@yanzhenjie 对我刚才说的话抱歉，我开发android 没多久。我现在呢，是想着通过SwipeMenuLayout的监听，在adapter 中，当我打开一个菜单的时候，控制已经打开的菜单关闭，就不想再封装listView 了

**Comment by yanzhenjie** [comment]
不封装ListView是不太可能实现的，如果要关闭其它Item，肯定要刷新其它Item，adapter.notify...这样效率更低，而且你的每一个列表都需要这么做。所以我建议你还是换成SwipeRecyclerView。

**Comment by fangshuai0119** [comment]
我可不可以效仿您的SwipeRecyclerView ，我在adapter 中加一个ItemView的弱引用，当我某一个ItemView打开时，我将以前打开的ItemView 的SwipeMenuLayout关闭，然后将当前ItemView 赋值给弱引用

**Comment by yanzhenjie** [comment]
具体我没有实验过，不知道可行不可行，你可以试试看。

**Comment by fangshuai0119** [comment]
@yanzhenjie 好的，我先把代码down下去，已经在修改了。刚才加群，被拒了。。。

**Comment by yanzhenjie** [comment]
你问题问题没回答吧，或者答错了，你重加下。

**Comment by fangshuai0119** [comment]
@yanzhenjie 我已经按照我上边的想法实现功能了，谢谢
