### ISSUE TITLE
NestedScrollView嵌套SwipeMenuRecyclerView和RecyclerView滑动不畅

### ISSUE THREAD

**Issue by gaobin881201** [yanzhenjie/SwipeRecyclerView#144]
在NestedScrollView嵌套SwipeMenuRecyclerView和RecyclerView设置android:nestedScrollingEnabled="false"属性。。发现滑动会有问题。。初始化的时候列表是不能滑动。。。替换成普通的RecyclerView发现没有问题，请问作者有试过这种场景么

**Comment by yanzhenjie** [comment]
在Java代码中：
```java
SwipeMenuRecyclerView.setNestedScrollingEnabled(false);
```

**Comment by yanerly** [comment]
SwipeMenuRecyclerView.setNestedScrollingEnabled(false);我加了这一句代码之后，滑动还是很卡，坐着知道怎么解决吗
