### ISSUE TITLE
BaseRecyclerViewAdapterHelper添加addFooterView的时候提示SwipeMenuRecyclerView未注册？

### ISSUE THREAD

**Issue by XMWP** [yanzhenjie/SwipeRecyclerView#146]
.IllegalStateException: Observer com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView$2@f1685cd was not registered.
addFooterView 里面是SwipeMenuRecyclerView  
当主SwipeMenuRecyclerView上下滑动！addFooterView 里的SwipeMenuRecyclerView 
ANR提示未注册控件！

**Comment by yanzhenjie** [comment]
和 #141 是同一个问题，统一到 #141 中。
