### ISSUE TITLE
初始无法加载更多。

### ISSUE THREAD

**Issue by wsparse** [yanzhenjie/SwipeRecyclerView#149]
加载更多时初始只加载5条数据（未满屏）无法出发加载更多条件，只有初始加载的数据条数达到满屏条件才能加载更多。

**Comment by yanzhenjie** [comment]
是的，有意这样设计的。  
https://github.com/yanzhenjie/SwipeRecyclerView/issues/149

**Comment by CoolEnoughSmile** [comment]
你好，我也有这种需求，初始数据不满屏就无法触发加载更多，请问有解决方案吗？
