### ISSUE TITLE
拖动item  以及设置不同item的menu的时候会出现滑动BUG

### ISSUE THREAD

**Issue by HunterVz** [yanzhenjie/SwipeRecyclerView#15]
当设置可以拖动排序以及item不同类型的时候 上下滑动会出现滑动卡顿UI出错，望大神早点解决

**Comment by yanzhenjie** [comment]
1. 不同类型也就是不同ViewType的Item之间默认是不允许拖动的，你可能是利用我自定义的那个例子写的。
2. 不同类型的item之间建议不要拖动，因为不同的item之间拖动需要重绘UI，会重新调用getContentView()、onCreateViewHolder等方法，由于系统机制，肯定会卡顿的，这个不可避免。
3. 如果你的情况不是我上述描述的这样，麻烦你可以弄一张GIF，上传到这个issue下，我好判断解决。

谢谢！

**Comment by HunterVz** [comment]
你说的就是我遇到的情况 我这边就是遇到的需求就是既可以拖动 又会item的menu不一样的 很蛋疼 不知道大神有没有解决的办法呢

**Comment by yanzhenjie** [comment]
不同的ViewType的Item之间不建议可以拖拽，就如我上文所说，这个是机制问题，不可避免。

**Comment by HunterVz** [comment]
好吧 那我在想想别的办法吧 谢谢了

**Comment by HunterVz** [comment]
代码写的很不错 学到了很多

**Comment by HunterVz** [comment]
我找到解决办法了  我不根据viewtype判断menu就可以了 通过bean里面的字段来控制GONE 就搞定了
