### ISSUE TITLE
自身有下拉刷新的功能吗

### ISSUE THREAD

**Issue by MrBoudar** [yanzhenjie/SwipeRecyclerView#158]
本身默认的情况下，有下拉刷新的功能吗，不想用谷歌的refresh控件

**Comment by yanzhenjie** [comment]
没有，没有限制，你想用啥都行。因为还有嵌套之类，还有其它布局之类的，这个只是做内容自动加载更多。

**Comment by MrBoudar** [comment]
行，我看看代码，自己改改
