### ISSUE TITLE
为什么我的侧滑删除没效果啊

### ISSUE THREAD

**Issue by kamike** [yanzhenjie/SwipeRecyclerView#159]
发现这样写效果没有出现侧滑的界面，但是可以侧滑删除

![2](https://user-images.githubusercontent.com/3920019/35610110-176f000c-069b-11e8-9993-f1a89ebe9cc6.jpg)

**Comment by yanzhenjie** [comment]
你侧滑的时候，想啥时候出现侧滑菜单，啥时候出现侧滑删除？意念控制吗？哈哈哈，这个只能二选一了。

**Comment by hezhipengzipp** [comment]
我也遇到了，怎么解决的呀

**Comment by parcool** [comment]
我也遇到了，怎么解决的呀
