### ISSUE TITLE
请问你的这个swiprecyclerView和https://github.com/jdsjlzx/LRecyclerView/有什么区别

### ISSUE THREAD

**Issue by nimengbo** [yanzhenjie/SwipeRecyclerView#16]
请问你的这个swiprecyclerView和https://github.com/jdsjlzx/LRecyclerView/   有什么区别

**Comment by junyuecao** [comment]
帮你拆一下url ： https://github.com/jdsjlzx/LRecyclerView/

**Comment by markzhai** [comment]
https://github.com/TUBB/SwipeMenu/
还有这个

**Comment by yanzhenjie** [comment]
LRecyclerView应该是直接搬了我的SwipeRecyclerView的。细心的人可以看看注释或者看看LRecyclerView中关于SwipeRecyclerView这块提交的时间，当然我和LRecyclerView的作者是认识的，LRecyclerView的项目主页下面也给SwipeRecyclerView了tks的。
SwipeRecyclerView地址：https://github.com/yanzhenjie/SwipeRecyclerView

**Comment by nimengbo** [comment]
@yanzhenjie  我看了目录结构和一些代码实现和https://github.com/TUBB/SwipeMenu/ 很像啊

**Comment by yanzhenjie** [comment]
@nimengbo 嗯嗯，我在ReadMe中做了说明了，之前一是没找到，二是也不没太注意到。谢谢各位的指正，做的不好的地方多多包含下，谢谢。
![qq 20160913152621](https://cloud.githubusercontent.com/assets/13534988/18464956/9f255306-79c6-11e6-8c3e-0d76d280a331.png)


![qq 20160913152653](https://cloud.githubusercontent.com/assets/13534988/18464963/a5ea74c8-79c6-11e6-90cd-c1756bcb5664.png)
