### ISSUE TITLE
recyclerview-swipe 结合new VegaLayoutManager()这个布局出现错误，请问如何解决

### ISSUE THREAD

**Issue by 1009256707** [yanzhenjie/SwipeRecyclerView#160]
recyclerview-swipe 结合new VegaLayoutManager()这个布局
https://github.com/xmuSistone/VegaLayoutManager 

，使用recycler_view.smoothScrollToPosition(0) 出现以下错误如何解决。
You must override smoothScrollToPosition to support smooth scrolling

**Comment by yanzhenjie** [comment]
SRV不会主动报这个错，所以不太清楚具体是什么引起的，也可能是底层报错，也可能是VLM报错，你可以去VLM问问看。
