### ISSUE TITLE
ArrayIndexOutOfBoundsException length=13; index=-1

### ISSUE THREAD

**Issue by pencilso** [yanzhenjie/SwipeRecyclerView#166]
线上异常收集，所收集到到堆栈信息。
从报错信息来看，好像是传入了一个-1 index进去，具体怎么传进去到，我也不知道 - -
1 android.support.v4.util.SparseArrayCompat.keyAt(SparseArrayCompat.java:240)
--
2 com.yanzhenjie.recyclerview.swipe.SwipeAdapterWrapper.getItemViewType(SwipeAdapterWrapper.java:88)
3 com.yanzhenjie.recyclerview.swipe.widget.DefaultItemDecoration.drawHorizontal(DefaultItemDecoration.java:164)
4 com.yanzhenjie.recyclerview.swipe.widget.DefaultItemDecoration.onDraw(DefaultItemDecoration.java:154)
5 android.support.v7.widget.RecyclerView.onDraw(RecyclerView.java:3934)
6 android.view.View.draw(View.java:16435)
7 android.support.v7.widget.RecyclerView.draw(RecyclerView.java:3869)
8 android.view.View.updateDisplayListIfDirty(View.java:15388)
9 android.view.View.draw(View.java:16189)
10 android.view.ViewGroup.drawChild(ViewGroup.java:3735)
11 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
12 android.view.View.updateDisplayListIfDirty(View.java:15380)
13 android.view.View.draw(View.java:16189)
14 android.view.ViewGroup.drawChild(ViewGroup.java:3735)
15 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
16 android.view.View.updateDisplayListIfDirty(View.java:15380)
17 android.view.View.draw(View.java:16189)
18 android.view.ViewGroup.drawChild(ViewGroup.java:3735)
19 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
20 android.view.View.updateDisplayListIfDirty(View.java:15380)
21 android.view.View.draw(View.java:16189)
22 android.view.ViewGroup.drawChild(ViewGroup.java:3735)
23 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
24 android.view.View.updateDisplayListIfDirty(View.java:15380)
25 android.view.View.draw(View.java:16189)
26 android.view.ViewGroup.drawChild(ViewGroup.java:3735)
27 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
28 android.view.View.updateDisplayListIfDirty(View.java:15380)
29 android.view.View.draw(View.java:16189)
30 android.view.ViewGroup.drawChild(ViewGroup.java:3735)
31 android.view.ViewGroup.dispatchDraw(ViewGroup.java:3525)
32 com.android.internal.policy.PhoneWindow$DecorView.dispatchDraw(PhoneWindow.java:2766)
33 android.view.View.draw(View.java:16447)
34 com.android.internal.policy.PhoneWindow$DecorView.draw(PhoneWindow.java:2752)
35 android.view.View.updateDisplayListIfDirty(View.java:15388)
36 android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:286)
37 android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:292)
38 android.view.ThreadedRenderer.draw(ThreadedRenderer.java:327)
39 android.view.ViewRootImpl.draw(ViewRootImpl.java:3030)
40 android.view.ViewRootImpl.performDraw(ViewRootImpl.java:2834)
41 android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2446)
42 android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1323)
43 android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:6718)
44 android.view.Choreographer$CallbackRecord.run(Choreographer.java:894)
45 android.view.Choreographer.doCallbacks(Choreographer.java:696)
46 android.view.Choreographer.doFrame(Choreographer.java:631)
47 android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:880)
48 android.os.Handler.handleCallback(Handler.java:815)
49 android.os.Handler.dispatchMessage(Handler.java:104)
50 android.os.Looper.loop(Looper.java:207)
51 android.app.ActivityThread.main(ActivityThread.java:5765)
52 java.lang.reflect.Method.invoke(Native Method)
53 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:789)
54 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:679)

**Comment by pencilso** [comment]
版本是1.1.2

**Comment by yanzhenjie** [comment]
我看你提交了一个PR，已经合并了，这个issue关闭了。

**Comment by pencilso** [comment]
老铁   这都多长时间了  你才看到啊
