### ISSUE TITLE
添加header头后，导致Item变形

### ISSUE THREAD

**Issue by pencilso** [yanzhenjie/SwipeRecyclerView#176]
GridLayoutManager  两列的Item
没添加Header头之前完好，但是添加之后，Item就变形了，好像被挤在一块一样

**Comment by yu893145181** [comment]
Grid 在添加头部的情况下，去添加DefaultDecoration分割线会有问题，楼主看下，我也遇到了

**Comment by pencilso** [comment]
MMP  他吗的  这个问题确实存在的  今天用这玩意的时候又碰到了，你他吗啥时候看看这个问题

**Comment by yanzhenjie** [comment]
Track #155.

**Comment by pencilso** [comment]
？？？？  为啥close了？
