### ISSUE TITLE
拖拽与下拉刷新冲突

### ISSUE THREAD

**Issue by gzejia** [yanzhenjie/SwipeRecyclerView#18]
当列表当中实现了侧滑菜单与拖拽的时候，上下拉刷新与拖拽会有冲突。

**Comment by ash-dragon** [comment]
public boolean isDragging;

    swipeRefreshLayout.setOnChildScrollUpCallback(new SwipeRefreshLayout.OnChildScrollUpCallback() {
            @Override
            public boolean canChildScrollUp(SwipeRefreshLayout parent, @Nullable View child) {
                return isDragging;
            }

        });
        swipeMenuRecyclerView.setOnItemStateChangedListener(new OnItemStateChangedListener() {
            @Override
            public void onSelectedChanged(RecyclerView.ViewHolder viewHolder, int actionState) {
                isDragging = actionState == OnItemStateChangedListener.ACTION_STATE_DRAG;
            }
        });
