### ISSUE TITLE
如何才能打开和禁用侧滑功能、下拉刷新功能

### ISSUE THREAD

**Issue by zhanyufengg** [yanzhenjie/SwipeRecyclerView#184]
你好！控件功能非常强大，可在项目中遇到在不同的状态下，需要禁用侧滑和刷新功能的情况，这时候如何才能实现？望能提供接口或者思路，感谢！

**Comment by Gitgitgitgghub** [comment]
不需要刷新可以 refreshLayout.setEnabled(false); 這是原生的功能
 不要側滑刪除 不要呼叫 recyclerView.setItemViewSwipeEnabled(true); 就好了，默認是關閉的
