### ISSUE TITLE
您好，按照readme中的方法设置上拉加载不起作用

### ISSUE THREAD

**Issue by cyixlq** [yanzhenjie/SwipeRecyclerView#185]
按照readme中的方法设置上拉加载不起作用，另外，我在RecyclerView外层是加了SwipeRefreshLayout的，不知道这个会不会影响，因为我看readme好像没有介绍如何添加下拉刷新的功能

**Comment by Xmaoyh** [comment]
你第一次加载数据也要调用loadMoreFinish(boolean dataEmpty, boolean hasMore)方法。。。我是这样解决的
