### ISSUE TITLE
作者：我为什么不加 下拉刷新与上拉加载？

### ISSUE THREAD

**Issue by choubaguai** [yanzhenjie/SwipeRecyclerView#2]
再加上下拉刷新，上拉加载，弄全面一点。

**Comment by yanzhenjie** [comment]
是一个不错的建议。这个我在写这个框架之前考虑过，下拉刷新和上拉加载是与我不同的概念，下拉刷新还是交给其它模块去做：http://blog.csdn.net/yanzhenjie1003/article/details/52115566

**Comment by jdsjlzx** [comment]
RecyclerView下拉刷新，自动加载更多：https://github.com/jdsjlzx/LRecyclerView

**Comment by Android-xiaole** [comment]
这个库现在实现了下拉刷新、下拉加载了吗？同求啊！

**Comment by jdsjlzx** [comment]
@Android-xiaole 看看这个能否满足你的 需求：https://github.com/jdsjlzx/LRecyclerView

**Comment by Android-xiaole** [comment]
@jdsjlzx mark! Thanks!
