### ISSUE TITLE
com.yanzhenjie.recyclerview.swipe.SwipeMenuLayout的bug

### ISSUE THREAD

**Issue by jlertele** [yanzhenjie/SwipeRecyclerView#20]
如果是在RecyclerView的onBindViewHolder调用smoothOpenLeftMenu方法，会出现部分item无法打开左侧按钮的情况，需要上下滑动RecyclerView好几次打开状态才正常

**Comment by yanzhenjie** [comment]
在onBindViewHolder中操作本来就是违规的，不能在适配器中操作，全部数据初始化完成后再打开。

**Comment by yanzhenjie** [comment]
点击某个item按钮可以打开对应的菜单，不能打开全部的，只能同事打开一个菜单。
