### ISSUE TITLE
菜单item长度设置了70dp但是运行起来依然很短。

### ISSUE THREAD

**Issue by JumpingError** [yanzhenjie/SwipeRecyclerView#200]
`private SwipeMenuCreator swipeMenuCreator = (swipeLeftMenu, swipeRightMenu, viewType) -> {
        SwipeMenuItem rightMenu = new SwipeMenuItem(mActivity);
        rightMenu.setText("删除");
        rightMenu.setBackgroundColor(getResources().getColor(R.color.point_red));
        rightMenu.setHeight(ViewGroup.LayoutParams.MATCH_PARENT);
        rightMenu.setWeight(getResources().getDimensionPixelSize(R.dimen.dp_70));
        rightMenu.setTextColor(getResources().getColor(R.color.white));
        SwipeMenuItem rightMenu2 = new SwipeMenuItem(mActivity);
        rightMenu2.setText("置顶");
        rightMenu2.setWeight(getResources().getDimensionPixelSize(R.dimen.dp_70));
        rightMenu2.setBackgroundColor(getResources().getColor(R.color.wight_grey));
        rightMenu2.setTextColor(getResources().getColor(R.color.white));
        rightMenu2.setHeight(ViewGroup.LayoutParams.MATCH_PARENT);
        swipeRightMenu.addMenuItem(rightMenu);
        swipeRightMenu.addMenuItem(rightMenu2);
    };
`

**Comment by MWLISATRUEMAN** [comment]
是setWidth()不是setWeigth(),老哥，我也找了半天，笑哭
