### ISSUE TITLE
Set Dynamic images on list item

### ISSUE THREAD

**Issue by Dhaval11296** [yanzhenjie/SwipeRecyclerView#202]
Hello yanzhenjie, i used this library for favorite & unfavorite item,
suppose i have 10 list and in this list 3 is favorite & 7 unfavorite so, how can i set favorite image in 3 item of list & how can i set unfavorite image in 7 item of list.

**Comment by yanzhenjie** [comment]
Now, starting with version 1.2.0, you only need to refresh the adapter to recreate the menu.
