### ISSUE TITLE
能否设置单个item的侧滑开关

### ISSUE THREAD

**Issue by Rosume** [yanzhenjie/SwipeRecyclerView#204]
也就是说满足一定条件的位置的item是不需要侧滑的，能不能加个开关禁用掉

**Comment by JunhuaLin** [comment]
我已经提交了该功能的代码 等待作者验证通过

**Comment by maolubin** [comment]
> 我已经提交了该功能的代码 等待作者验证通过

现在版本我一刷新，就都能侧滑了，demo里的listActivity也一样
