### ISSUE TITLE
请问侧滑菜单能否动态改变

### ISSUE THREAD

**Issue by zcycn** [yanzhenjie/SwipeRecyclerView#21]
比如两项变三项或文字改变

**Comment by zcycn** [comment]
@yanzhenjie 谢谢，再咨询下，SwipeMenuRecyclerView能否设置是否允许菜单滑动显示，就是有时需要整体禁用侧滑菜单

**Comment by yanzhenjie** [comment]
@zcycn 暂时不能，下个版本我将优化这个功能。

**Comment by zcycn** [comment]
@yanzhenjie think you
