### ISSUE TITLE
滑动删除直接消失了， 没有出现删除界面

### ISSUE THREAD

**Issue by Edwares** [yanzhenjie/SwipeRecyclerView#215]
recyclerView.setItemViewSwipeEnabled(true);
        recyclerView.setSwipeMenuCreator(new SwipeMenuCreator() {
            @Override
            public void onCreateMenu(SwipeMenu swipeLeftMenu, SwipeMenu swipeRightMenu, int viewType) {
                int width = PxAndDpUtils.dip2px(mContext, 70);
                int height = ViewGroup.LayoutParams.MATCH_PARENT;
                SwipeMenuItem deleteItem = new SwipeMenuItem(mContext)
                        .setBackgroundColor(getResources().getColor(R.color.red))
                        .setTextColor(getResources().getColor(R.color.white))
                        .setText("删除")
                        .setHeight(height)
                        .setWidth(width);
                swipeRightMenu.addMenuItem(deleteItem);
            }
        });
我滑动item的时候，直接就变淡然后消失了，还调用了`
`      @Override
            public void onItemDismiss(RecyclerView.ViewHolder srcHolder) {
                print("item 消失了");
            }`
请问是什么原因呢

**Comment by yanzhenjie** [comment]
就是这样的。

**Comment by Edwares** [comment]
怎么才能显示侧滑删除的那个按钮呢

**Comment by qq1100** [comment]
我也出现同样的情况，侧滑显示不了布局
