### ISSUE TITLE
大哥怎么指定某个item不能进行侧滑菜单啊

### ISSUE THREAD

**Issue by maolubin** [yanzhenjie/SwipeRecyclerView#217]

**Comment by lerpo** [comment]
`holder.itemView.setOnTouchListener(new View.OnTouchListener() {
                float startIndex = 0;
                float endIndex = 0;
                @Override
                public boolean onTouch(View v, MotionEvent event) {

                   switch (event.getAction()) {
                       case MotionEvent.ACTION_DOWN:{
                           startIndex = event.getX();
                       }break;
                       case  MotionEvent.ACTION_UP:{
                           endIndex = event.getX();
                       }break;
                       case MotionEvent.ACTION_MOVE:{
                           endIndex = event.getX();
                       }break;
                   }
                   if(endIndex != 0 && Math.abs(endIndex-startIndex) > 5) {
                       return true;
                   }else {
                       return false;
                   }
                }
            });`
兄弟 我也遇到这个需求了，我目前是把指定的item左右滑动事件给拦截了，我目前是这么做的

**Comment by yanzhenjie** [comment]
recyclerView.setSwipeItemMenuEnabled(boolean); // 禁止或者启用所有侧滑菜单
recyclerView.setSwipeItemMenuEnabled(int, boolean); // 禁止或者启用某个Item的侧滑菜单

**Comment by maolubin** [comment]
> `holder.itemView.setOnTouchListener(new View.OnTouchListener() {
> float startIndex = 0;
> float endIndex = 0;
> @override
> public boolean onTouch(View v, MotionEvent event) {
> 
> ```
>                switch (event.getAction()) {
>                    case MotionEvent.ACTION_DOWN:{
>                        startIndex = event.getX();
>                    }break;
>                    case  MotionEvent.ACTION_UP:{
>                        endIndex = event.getX();
>                    }break;
>                    case MotionEvent.ACTION_MOVE:{
>                        endIndex = event.getX();
>                    }break;
>                }
>                if(endIndex != 0 && Math.abs(endIndex-startIndex) > 5) {
>                    return true;
>                }else {
>                    return false;
>                }
>             }
>         });`
> ```
> 兄弟 我也遇到这个需求了，我目前是把指定的item左右滑动事件给拦截了，我目前是这么做的

我item位置不固定的，本来那个设置的没有侧滑菜单，一刷新后，就可以侧滑了，菜单也自动加上了

**Comment by maolubin** [comment]
> recyclerView.setSwipeItemMenuEnabled(boolean); // 禁止或者启用所有侧滑菜单
> recyclerView.setSwipeItemMenuEnabled(int, boolean); // 禁止或者启用某个Item的侧滑菜单

调了没用，第二个
