### ISSUE TITLE
混淆 support 库 SwipeAdapterWrapper中的反射出错

### ISSUE THREAD

**Issue by windvip** [yanzhenjie/SwipeRecyclerView#218]
混淆 support 库，无法使用此库。
SwipeAdapterWrapper#onCreateViewHolder() {
    Field itemView = getSupperClass(viewHolder.getClass()).getDeclaredField("itemView");
}

**Comment by yanzhenjie** [comment]
旧版本请查看[release](https://github.com/yanzhenjie/SwipeRecyclerView/releases)中对应的README，最新版本不需要添加混淆。
