### ISSUE TITLE
我数据不为空，但是SwipeRecyclerView 不显示

### ISSUE THREAD

**Issue by panrongfu** [yanzhenjie/SwipeRecyclerView#22]
```
  步骤： 
   systemMsgAdapter = new SystemMsgAdapter(messageItems);
    systemMsgAdapter.setOnItemClickListener(onItemClickListener);
    systemMsgAdapter.setOnItemChildButtonListener(onItemChildButtonListener);
    binding.recyclerView.setAdapter(systemMsgAdapter);
但是：
  在适配器中 以下四个方法没有调用
```

 @Override
    public View onCreateContentView(ViewGroup parent, int viewType) {
        return LayoutInflater.from(parent.getContext()).inflate(R.layout.sys_msg_item_layout, parent, false);
    }

```
@Override
public SystemMsgAdapter.SystemMsgViewHolder onCompatCreateViewHolder(View realContentView, int viewType) {
    return new SystemMsgViewHolder(realContentView);
}

@Override
public void onBindViewHolder(SystemMsgAdapter.SystemMsgViewHolder holder, final int position)
```

   @Override
    public int getItemCount() {
        return null==systemMessages ? 0 : systemMessages.size();
    }

**Comment by 354420603** [comment]
我也遇到同样的问题了我显现只有在4.4系统的手机上出现，改怎么解决呀

**Comment by yanzhenjie** [comment]
@panrongfu 的问题可能是你xml中用的不是`SwipeRecyclerView`，还有就是`DataBinding`目前还不是很稳定，不建议使用。
@354420603 你的问题把具体的代码和错误能不能贴出来一下，或者说升级一下`RecyclerView`的版本试试，我刚发布了新版，使用了`support 25.2.0`版，你可以升级后再试试。

**Comment by 354420603** [comment]
yan大大是我自己的问题我做蓝牙这块的我在非UI线程里改动UI所以没有刷新出数据

**Comment by 354420603** [comment]
有点sb了

**Comment by raighneweng** [comment]
databinding是怎么实现的？onCompatCreateViewHolder只能return一个view。
