### ISSUE TITLE
可以设置侧滑按钮的位置吗，gravity

### ISSUE THREAD

**Issue by po1arbear** [yanzhenjie/SwipeRecyclerView#228]

**Comment by po1arbear** [comment]
高度不是match_parent的时候如何删除按钮centerVertical?

**Comment by yanzhenjie** [comment]
不能，必须居中。

**Comment by po1arbear** [comment]
现在的情况是删除按钮相对于item没有竖直居中，item的高度为h+margin 删除按钮高度为h，导致按钮偏上

**Comment by yanzhenjie** [comment]
第一个选择，使用match_parent，第二个设置具体高度，具体告诉为item的完整高度。

**Comment by po1arbear** [comment]
我的itemView是一个cardview，如果设置match_parent删除按钮在视觉上会比itemview宽很多，
如果设置固定高度，想在视觉上达到一样的高度，删除按钮的高度就会比Item小，布局会偏上，不知是否自己的操作有问题？

**Comment by yanzhenjie** [comment]
cardview可以参考demo。

**Comment by po1arbear** [comment]
我去看看，多谢严大
