### ISSUE TITLE
加载更多结束后，怎继续往上滚动啊 

### ISSUE THREAD

**Issue by littlezan** [yanzhenjie/SwipeRecyclerView#231]
demo中的代码，一行未改
效果图
![gif](https://user-images.githubusercontent.com/5358278/51081361-cc95a280-1728-11e9-9489-be41c219a3dc.gif)

**Comment by yanzhenjie** [comment]
用手向上滑动。

**Comment by littlezan** [comment]
我是用手向上滑动的哈
