### ISSUE TITLE
新版本1.3.0在as3.1.2xml上一直找不到SwipeRecyclerView，换了下老版本的as2.3.2有

### ISSUE THREAD

**Issue by 920651004** [yanzhenjie/SwipeRecyclerView#238]
![image](https://user-images.githubusercontent.com/15808839/52605854-6c228e00-2eab-11e9-9450-90f8a2973406.png)

**Comment by yanzhenjie** [comment]
使用的是support库还是x库？

**Comment by 920651004** [comment]
support，在as3.1.2上面support和x我都换了都找不到SwipeRecyclerView

**Comment by yanzhenjie** [comment]
我新建了一个项目，添加远程依赖后，都可以找到。

看你的截图，可能是提示问题，你尝试敲SwipeRecyclerView，然后`alt + /`试试。

**Comment by 920651004** [comment]
有点奇怪，不知道我的as抽筋了还是怎么了，我让我同事远程依赖之后就可以找到同样的版本的as
