### ISSUE TITLE
改进建议

### ISSUE THREAD

**Issue by androidWht** [yanzhenjie/SwipeRecyclerView#241]
1 支持根据position来刷新menuView
       例如在onBindView中添加回调方法onRefreshMenu(SwipeMenuBridge menu)
2 支持根据position来设置是否显示menu
      例如添加回调方法enableMenu(int position)

**Comment by yanzhenjie** [comment]
这两个都是支持的呀。
* 第一个：
调用`Adapter#notifyItemChanged(int)`时会重新调用`SwipeMenuCreator#onCreateMenu()`，这时可以根据当前Item的Data来决定菜单需要怎么显示，还是不显示。

* 第二个：
  * `SwipeRecyclerView#setSwipeItemMenuEnabled(boolean)`设置所有Item的Menu能否滑开
  * `SwipeRecyclerView#isSwipeItemMenuEnabled()`判断所有Item的Menu能否滑开
  * `SwipeRecyclerView#setSwipeItemMenuEnabled(boolean, int)`设置某个Item的Menu能否滑开
  * `SwipeRecyclerView#isSwipeItemMenuEnabled(int)`判断某个Item的Menu能否滑开

**注意**：第二点中的滑开指的是**控制用户手势滑动打开**，但`smoothOpenMenu()`和`smoothCloseMenu()`系列方法是代码控制主动打开，不受上述设置方法影响。

**Comment by androidWht** [comment]
第二点我看下。
第一点我还是不太明白，现在item的menu视图内容只有在onCreateViewHolder时根据viewType创建，并没有在onBindViewHolder时刷新的功能。我的adapter数据内容并没有变化，不可能去调用notifyItemChanged，我根本不知道在什么时机调用，假如每一个position的menu视图内容都不一样呢。
我的意思能不能提供像Adapter ItemView一样的创建和刷新机制。

![image](https://user-images.githubusercontent.com/10459917/53063219-5d1c8b00-34fe-11e9-84cc-512f3c51ba05.png)

**Comment by yanzhenjie** [comment]
你用的版本应该很老了，从1.2.3时就支持了。

**Comment by androidWht** [comment]
哦哦，知道了，谢谢！
