### ISSUE TITLE
侧滑菜单按钮如何居中？

### ISSUE THREAD

**Issue by BeatGeneration** [yanzhenjie/SwipeRecyclerView#242]
![question](https://user-images.githubusercontent.com/24977381/53063984-17ad8d00-3501-11e9-8469-057efd97f8a9.jpg)

如图，侧滑按钮我是自定义的高度，如何让按钮居中

**Comment by yanzhenjie** [comment]
这种比Item矮的操作是我没想到的，所以忘记为这些menu添加垂直居中了，你可以先用和Item一样高，昨天刚发了新版本，近期没大问题应该不会发布新版本了。但是后面的新版本会修改这个问题。

**Comment by BeatGeneration** [comment]
好的，感谢！
