### ISSUE TITLE
SwipeMenuRecyclerView移除了吧

### ISSUE THREAD

**Issue by clanaid** [yanzhenjie/SwipeRecyclerView#245]
SwipeMenuRecyclerView在最新的版本里没有这个类了吧，README文档还保留写这个类的使用方法

**Comment by yanzhenjie** [comment]
抱歉，刚才点错了。

新版修改了一小部分包命、方法名和参数名，旧版依然是稳定的，但是新版添加了一些功能，所以用旧版的一些名称需要修改。

**Comment by clanaid** [comment]
嗯，我只是疑惑为什么文档上还有旧版的类名在，有点混淆了

**Comment by yanzhenjie** [comment]
已经更新了。
