### ISSUE TITLE
没办法实现一个RecycleView既可以侧滑删除 又可以上拉和下拉加载 还可以根据分组悬浮头部么?

### ISSUE THREAD

**Issue by KateChris** [yanzhenjie/SwipeRecyclerView#246]
<androidx.swiperefreshlayout.widget.SwipeRefreshLayout
        android:id="@+id/refresh_layout"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        app:layout_behavior="@string/appbar_scrolling_view_behavior">

        <com.yanzhenjie.recyclerview.widget.StickyNestedScrollView
            android:id="@+id/scroll_view"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            app:layout_behavior="@string/appbar_scrolling_view_behavior">

            <com.yanzhenjie.recyclerview.SwipeRecyclerView
                android:id="@+id/recycler_view"
                android:layout_width="match_parent"
                android:layout_height="wrap_content" />
        </com.yanzhenjie.recyclerview.widget.StickyNestedScrollView>
    </androidx.swiperefreshlayout.widget.SwipeRefreshLayout>

这种写法没法兼容 上拉加载无法正常使用

**Comment by yanzhenjie** [comment]
悬浮分组头部这个暂时没有实现。

**Comment by KateChris** [comment]
感谢 已经帮了大忙了
