### ISSUE TITLE
快速滑动容错问题

### ISSUE THREAD

**Issue by FrankZhang007** [yanzhenjie/SwipeRecyclerView#25]
快速滑动经常滑不了

**Comment by angcyo** [comment]
+1

**Comment by angcyo** [comment]
SwipeMenuRecyclerView  中的:
//
 private boolean handleUnDown(int x, int y, boolean defaultValue) {
        int disX = mDownX - x;
        int disY = mDownY - y;
        // swipe
        if (Math.abs(disX) > mViewConfig.getScaledTouchSlop())
            defaultValue = false;
        // click
        if (Math.abs(disY) < mViewConfig.getScaledTouchSlop() && Math.abs(disX) < mViewConfig.getScaledTouchSlop())
            defaultValue = false;
        return defaultValue;
    }

修改成:
if (Math.abs(disX) > mViewConfig.getScaledTouchSlop() && Math.abs(disX) > Math.abs(disY))
            defaultValue = false;
