### ISSUE TITLE
更新库了麻烦更新一下readme里的示例用法

### ISSUE THREAD

**Issue by ouerfeiyu** [yanzhenjie/SwipeRecyclerView#255]
花时间去依赖库，学习使用，搞了半天，结果有bug，侧滑菜单显示不出来，这不是浪费人的时间吗。
![图片](https://user-images.githubusercontent.com/36292231/55776792-74283400-5ad0-11e9-9163-131bca307011.png)
![图片](https://user-images.githubusercontent.com/36292231/55776803-7b4f4200-5ad0-11e9-99ed-41b9eac4fb91.png)

**Comment by yanzhenjie** [comment]
谢谢您的反馈，首先我会继续优化，其次我给您的建议解决方案就是换一个项目使用。

这只是个开源项目，选择开源项目使用时请选择适合自己的，如果项目的说明和Demo不适合自己，就不要使用。
