### ISSUE TITLE
建议增加单个item能否拖动或者滑动回调

### ISSUE THREAD

**Issue by vudiy** [yanzhenjie/SwipeRecyclerView#256]
建议增加单个item能否拖动或者滑动回调，并不是现在默认所有的item的行为一致

**Comment by yanzhenjie** [comment]
支持，设置`OnItemMovementListener`即可。

**Comment by vudiy** [comment]
OnItemMovementListener里面的onItemMove是判断拖拽后是否能移动，而我说的是item是否能拖拽

**Comment by vudiy** [comment]
@yanzhenjie

**Comment by yanzhenjie** [comment]
你看错类了吧。

**Comment by vudiy** [comment]
非常抱歉，确实看错了
