### ISSUE TITLE
源码下载下来运行后点击Item的拖拽和侧滑删除停止运行

### ISSUE THREAD

**Issue by ghost** [yanzhenjie/SwipeRecyclerView#263]
Didn't find class "android.support.v7.widget.SwitchCompat" on path: DexPathList[[zip file "/data/app/com.yanzhenjie.recyclerview.sample-64wuMZyH0LEG2CboiSrb2Q==/base.apk", zip file "/system/framework/org.apache.http.legacy.boot.jar"],nativeLibraryDirectories=[/data/app/com.yanzhenjie.recyclerview.sample-64wuMZyH0LEG2CboiSrb2Q==/lib/arm64, /system/lib64]]

**Comment by ghost** [comment]
> Didn't find class "android.support.v7.widget.SwitchCompat" on path: DexPathList[[zip file "/data/app/com.yanzhenjie.recyclerview.sample-64wuMZyH0LEG2CboiSrb2Q==/base.apk", zip file "/system/framework/org.apache.http.legacy.boot.jar"],nativeLibraryDirectories=[/data/app/com.yanzhenjie.recyclerview.sample-64wuMZyH0LEG2CboiSrb2Q==/lib/arm64, /system/lib64]]

**Comment by allenZ7** [comment]
请问下您的解决办法是什么呢？
