### ISSUE TITLE
侧滑menu设置宽度无效(.setWidth())

### ISSUE THREAD

**Issue by LZKDreamer** [yanzhenjie/SwipeRecyclerView#272]

**Comment by yanzhenjie** [comment]
不可能吧，莫不是写错单词了？weight？

**Comment by LZKDreamer** [comment]
是的，我把setWidth写成了setWeight（），已经解决了，不好意思




------------------ 原始邮件 ------------------
发件人: "Zhenjie Yan"<notifications@github.com>;
发送时间: 2019年7月10日(星期三) 下午2:32
收件人: "yanzhenjie/SwipeRecyclerView"<SwipeRecyclerView@noreply.github.com>;
抄送: "卧龙跃马"<1254233340@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [yanzhenjie/SwipeRecyclerView] 侧滑menu设置宽度无效(.setWidth()) (#272)




不可能吧，莫不是写错单词了？weight？
