### ISSUE TITLE
Adapter一定要继承SwipeMenuAdapter吗？

### ISSUE THREAD

**Issue by 121880399** [yanzhenjie/SwipeRecyclerView#28]
用到databinding ，不想改Adapter，可以不继承SwipeMenuAdapter吗？用TabLayout+viewpager 滑动没反应。

**Comment by yanzhenjie** [comment]
是哒，必须继承SwipeMenuAdapter。

**Comment by 121880399** [comment]
@yanzhenjie  看demo里面，SwipeMenuCreator只能设置Menu的宽高，可以设置他的位置吗？或者说有直接写在XML中的方式吗？

**Comment by yanzhenjie** [comment]
确定宽高、自适应宽高、icon、文字、文字颜色、文字style、横向还是竖向这些都可以设置，menu的位置只能在item的右边或者左边。

**Comment by 121880399** [comment]
@yanzhenjie  我的意思是，比如menu在右边，但是他的高度 不是匹配整个item，相当于设置了padding一样，上下都缩进一定距离

**Comment by yanzhenjie** [comment]
上面也说了可以指定menu的item的宽高，都是居中的。
