### ISSUE TITLE
NestedScrollView嵌套SwipeMenuRecyclerView后加载更多不可用

### ISSUE THREAD

**Issue by sunnycoffee** [yanzhenjie/SwipeRecyclerView#282]
NestedScrollView嵌套SwipeMenuRecyclerView会导致滑动不流畅，设置了setNestedScrollingEnabled(false)后SwipeMenuRecyclerView的onScrolled方法不被调用，导致无法完成下列加载更多。有啥简单的方法让外部滑动触发加载更多逻辑

**Comment by yanzhenjie** [comment]
做不到。
