### ISSUE TITLE
ListView显示有问题

### ISSUE THREAD

**Issue by JK520** [yanzhenjie/SwipeRecyclerView#3]
代码里面是写显示30条，实际上只有29条，而且分割线计算也有错误，我是参考：[http://blog.csdn.net/lmj623565791/article/details/45059587](url)

**Comment by yanzhenjie** [comment]
1. 首先假设你说的是demo，for循环了30个，index从0开始，到29，`0`是第1个，`1`是第2个......`29`是第30个，所以你看到的最后一条显示29。
2. 其次假设你说的你自己写的，这个库是做侧滑菜单和长安拖拽的，这个数据和分割线是开发者自己来做的，库不会对数据和分割线有任何影响，如果真出现了问题，那很有可能是你自己弄错了哦。
3. 最后如果还有问题欢迎继续讨论，或者加我的交流群交流，谢谢支持！

**Comment by JK520** [comment]
只显示到28

**Comment by yanzhenjie** [comment]
我这边和其它人都是对的。我Demo应该是对的，如果你用了别人的分割线或者其它那可能你要排查一下了。
如果还有问题请描述清楚一些，以方便解决问题。
