### ISSUE TITLE
不创建侧滑菜单整个SwipeRecyclerView只会显示一个item

### ISSUE THREAD

**Issue by Android-xiaole** [yanzhenjie/SwipeRecyclerView#31]
如果我的数据源里面只要有一个不创建侧滑菜单，那么这个SwipeRecyclerView就只显示一个item，这应该是BUG吧

**Comment by yanzhenjie** [comment]
SwipeRecyclerView没有做item的显示控制，我demo里有不显示菜单的item例子，不知道和你描述的是否一样，可否麻烦你看一下demo后再给我一个反馈？谢谢了。

**Comment by Android-xiaole** [comment]
不好意思 是我这边一个布局文件写的有点问题  让我误以为只显示一个item其实是只是充满整个屏幕了  这不是bug! 这不是bug! 这不是bug! 重要的事说三遍！抱歉...
