### ISSUE TITLE
怎么通过item的一个按钮拖拽?

### ISSUE THREAD

**Issue by shoushuai** [yanzhenjie/SwipeRecyclerView#36]
1. 不要开启长按拖拽，像拖拽的时候可以指定拖拽某个ViewHolder的，SwipeRecyclerView.startDrag...(ViewHolder)，也就是说你可以在ViewHolder中手指按下或者触摸到某个按钮的时候调用这个方法开始拖拽。我看到这个,不知道怎么改.

**Comment by yanzhenjie** [comment]
你可以把`SwipeRecyclerView`传到`adapter`中，给你的`item`的某个`view`设置`setOnTouchListener()`，监听到手指按下时当然可以知道这个被按下`view`所在的`viewHolder`了，此时调用`SwipeRecyclerView#startDrag()`。

**Comment by shoushuai** [comment]
谢谢严大,成功了
