### ISSUE TITLE
拖拽移动后的整个适配器的刷新

### ISSUE THREAD

**Issue by shoushuai** [yanzhenjie/SwipeRecyclerView#37]
严大,现在Item前面有CheckBox,需要保存状态集合,item拖拽调用了mAdapter.notifyItemMoved(fromPosition, toPosition);没有刷新整个适配器,导致第一次点击CheckBox时错位(还保留着原pos),之后点击没问题(刷新了整个适配器),在哪能调用刷新整个适配器呢?手势抬起时调用吗(遇到ACTION_DOWN正常,但ACTION_UP不执行)?

**Comment by yanzhenjie** [comment]
你的这个问题就算你使用`SwipeRecyclerView`也会有的，我推断是你用法上有点问题。
我估计是你`adapter`写错了什么，用`Item`对应的`Entity`去记这个这个`Item`的`CheckBox`的选中状态，这样调用如下代码后局部刷新收，Item也会刷新：
```java
@Override
public boolean onItemMove(int fromPosition, int toPosition) {
     Collections.swap(mDataList, fromPosition, toPosition);
     mMenuAdapter.notifyItemMoved(fromPosition, toPosition);
     return true;
}
```
