### ISSUE TITLE
GridView 图片达到两行交换后，获取数据源，发现数据源数据顺序并不是列表中的顺序

### ISSUE THREAD

**Issue by fangcaiwen** [yanzhenjie/SwipeRecyclerView#38]
GridView 图片达到两行交换后，获取数据源，发现数据源数据顺序并不是列表中的顺序

**Comment by yanzhenjie** [comment]
是demo中的数据转换计算错误了，下面给出正确事例：
如果是Grid形式的：
```java
    private OnItemMoveListener onItemMoveListener = new OnItemMoveListener() {
        @Override
        public boolean onItemMove(int fromPosition, int toPosition) {
            // 拖拽item。
            if (fromPosition < toPosition)
                for (int i = fromPosition; i < toPosition; i++)
                    Collections.swap(mDataList, i, i + 1);
            else
                for (int i = fromPosition; i > toPosition; i--)
                    Collections.swap(mDataList, i, i - 1);

            mMenuAdapter.notifyItemMoved(fromPosition, toPosition);
            return true;
        }

        @Override
        public void onItemDismiss(int position) {
            // 侧滑删除。
            mDataList.remove(position);
            mMenuAdapter.notifyItemRemoved(position);
        }
    };
```

如果是List形式的：
```java
    private OnItemMoveListener onItemMoveListener = new OnItemMoveListener() {
        @Override
        public boolean onItemMove(int fromPosition, int toPosition) {
            Collections.swap(mDataList, fromPosition, toPosition);
            mMenuAdapter.notifyItemMoved(fromPosition, toPosition);
            return true;
        }

        @Override
        public void onItemDismiss(int position) {
            // 侧滑删除。
            mDataList.remove(position);
            mMenuAdapter.notifyItemRemoved(position);
        }
    };
```

**Comment by fangcaiwen** [comment]
我自己做了处理，我感觉Collections.swap这个方法是直接换取数据里面两个元素的位置。而交换是直接把一张图片插到某一个位置，所以我采取的方式是循环移动元素再插入，你看看是否正确
 private OnItemMoveListener onItemMoveListener = new OnItemMoveListener() {
        @Override
        public boolean onItemMove(int fromPosition, int toPosition) {
//            Collections.swap(mStrings, fromPosition, toPosition);
            if(fromPosition>toPosition){
                String lastStr=mStrings.get(fromPosition);
                for(int i = fromPosition; i>= toPosition+1; i--) {
                    mStrings.set(i,mStrings.get(i-1));
                }
                mStrings.set(toPosition,lastStr);
            }else{
                String firstStr=mStrings.get(fromPosition);
                for(int i = fromPosition; i<= toPosition-1; i++) {
                    mStrings.set(i,mStrings.get(i+1));
                }
                mStrings.set(toPosition,firstStr);
            }

            mMenuAdapter.notifyItemMoved(fromPosition, toPosition);
            return true;// 返回true表示处理了，返回false表示你没有处理。
        }

        @Override
        public void onItemDismiss(int position) {
            // 当Item被滑动删除掉的时候，在这里是无效的，因为这里没有启用这个功能。
            // 使用Menu时就不用使用这个侧滑删除啦，两个是冲突的。
            mStrings.remove(position);
            mMenuAdapter.notifyItemRemoved(position);
//            Toast.makeText(DragImageActivity.this, "现在的第" + position + "条被删除。", Toast.LENGTH_SHORT).show();
        }
    };
