### ISSUE TITLE
事件冲突，数据显示不全

### ISSUE THREAD

**Issue by Yanqilong** [yanzhenjie/SwipeRecyclerView#39]
Scrollview嵌套SwipeMenuRecyclerView，数据显示不全。如果继承SwipeMenuRecyclerView并重写dispatchTouchEvent和onMeasure方法，那么数据显示没有问题，带来的新问题是item项不能左右滑动，请问怎么解决？

//通过重新dispatchTouchEvent方法来禁止滑动
    @Override
    public boolean dispatchTouchEvent(MotionEvent ev) {
        if (ev.getAction() == MotionEvent.ACTION_MOVE) {
            return false;
        }
        return super.dispatchTouchEvent(ev);
    }

    @Override
    public void onMeasure(int widthMeasureSpec, int heightMeasureSpec) {
        int expandSpec = MeasureSpec.makeMeasureSpec(
                Integer.MAX_VALUE >> 2, MeasureSpec.AT_MOST);
        super.onMeasure(widthMeasureSpec, expandSpec);
    }

**Comment by yanzhenjie** [comment]
ScrollView嵌套RecyclerView不存在数据显示不完全的情况，如果存在请升级你的RecyclerView库版本。
