### ISSUE TITLE
已修复：viewpager 滑动冲突

### ISSUE THREAD

**Issue by IJustHave** [yanzhenjie/SwipeRecyclerView#4]
swipeRecyclerview 在viewpager中使用滑动冲突，有没有好的解决办法？谢谢

**Comment by yanzhenjie** [comment]
暂时不支持与ViewPager嵌套使用。目前QQ和微信使用的SwipeListView也是没有解决这个问题的。如果你们有好的方案可以PR上来。谢谢。

**Comment by yanzhenjie** [comment]
已经解决，欢迎继续使用，谢谢。
