### ISSUE TITLE
在有侧滑菜单的时候，点击Item里面的Button控件时，会导致崩溃

### ISSUE THREAD

**Issue by GitACDreamer** [yanzhenjie/SwipeRecyclerView#41]
在列表中有可点击的**按钮**并且这个item是有侧滑菜单时，点击**按钮**会导致崩溃
在  `SwipeMenuLayout` 页面第173行boolean` isClick = mSwipeCurrentHorizontal.isClickOnContentView(getWidth(), ev.getX());`  其中`mSwipeCurrentHorizontal=null` ，如果没有侧滑菜单时，我点击按钮是没有问题的可以响应按钮事件，此现象可以重现

**Comment by yanzhenjie** [comment]
感谢反馈，已修复，发布了1.0.4，请更新使用即可。
