### ISSUE TITLE
侧滑菜单应该考虑增加自适应高度

### ISSUE THREAD

**Issue by Kongdy** [yanzhenjie/SwipeRecyclerView#42]
目前侧滑菜单的高度需要指定，在不同分辨率下，即便跟item给定一个高度数值，还是会造成高度不一致导致的产生空白。

**Comment by yanzhenjie** [comment]
关于menu的高度问题，有三种选择，README中有加粗说明：
> 使用`MATCH_PARENT`将和`Item`高度一致；使用`WRAP_CONTENT`将和设置的文字或者图片一样高；也可以指定菜单具体高度，比如：`100`，这里的`100`是px，如果要传入dp，请先把dp转为px后再传入。

另外demo也明确给了实例和说明。
