### ISSUE TITLE
能添加对ScrollView的适配？

### ISSUE THREAD

**Issue by 52932** [yanzhenjie/SwipeRecyclerView#46]

**Comment by yanzhenjie** [comment]
目前没有发现问题，请详细描述你遇到的问题。

**Comment by anlzy** [comment]
<LinearLayout
        android:layout_width="match_parent"
        android:layout_height="match_parent">
        <com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView
            android:id="@+id/srv_authbind_bindrecyclerview"
            android:layout_width="match_parent"
            android:layout_height="match_parent"
            app:mainLayoutId="@layout/layout_recyclerview_verticalscroll"
            app:layout_moreProgress="@layout/view_more_progress"
            app:recyclerClipToPadding="true"
            app:scrollbarStyle="outsideOverlay"
            android:background="@color/friendgroup_bg"
            android:layout_marginTop="2dip"/>
    </LinearLayout> 
 这样菜单会滑不出来

**Comment by yanzhenjie** [comment]
我这里是可以滑出来的，demo中也有普通layout嵌套SwipeMenuRecyclerView的例子。
