### ISSUE TITLE
ViewPage

### ISSUE THREAD

**Issue by shenxiaolin** [yanzhenjie/SwipeRecyclerView#48]

**Comment by shenxiaolin** [comment]
ViewPager 的使用体验问题；
只能往一个方向上滑动ViewPager，然后另一个方向上出现滑动recycleviewItem的滑动删除；
有什么方案可以兼容吗？

**Comment by yanzhenjie** [comment]
没看懂什么意思。

**Comment by pp1991412** [comment]
就是viewpager+fragment实现的多界面，例如我们的列表recylceview 只实现左滑删除，而且这个列表在viewpager的最右面，这样我们viewpager向右滑动的时候，会不会跟 当前recycleview的侧滑删除冲突，虽然我们只用了左滑删除。如果这样看不懂，当我没说，或者换句话，viewpager+fragment实现的界面，用这个东西一定会冲突了吗？
