### ISSUE TITLE
上下滑动不能容错

### ISSUE THREAD

**Issue by fcq599301283** [yanzhenjie/SwipeRecyclerView#5]
在快速滑动时  滑动方向必须近乎垂直才能上下滑动   稍有弧度就不出现不滑动或弹出侧滑菜单情况  而用户习惯用大拇指来滑动屏幕 不可避免带有弧度

**Comment by yanzhenjie** [comment]
感谢反馈，已记录，会尽快优化！

**Comment by ArthurWangYB** [comment]
我提出的也是这个意思，不过没有楼主理解透彻啊
