### ISSUE TITLE
如果每个Item的高度不一致，无法写死每个划出的高度。怎解？

### ISSUE THREAD

**Issue by s162738** [yanzhenjie/SwipeRecyclerView#6]
如题？望大神解决

**Comment by yanzhenjie** [comment]
针对每个item的高度不一致，一般都会计算出item的高度来提高性能。
1. item的高度怎么计算出，这个就怎么计算。提示：根据ViewType。
2. 每个Item的高度不一样，但是每个Item的高度是可以计算出来是一定的，计算出来后给item设置一个高度（在BindViewHolder时设置ViewHolder.itemView的高度），menu的高度就写成match_parent，因为menu是在item中的。

**Comment by s162738** [comment]
本来想通过 onBindViewHolder 中计算出每个Item的高度来 给 onCreateMenu  中进行高度赋值。
但是你这个方法居然在 onBindViewHolder 之前执行。这样我还真不知道怎么得到出每个Item的高度了。
SwipeMenuItem deleteItem = new SwipeMenuItem(mContext)        .setBackgroundDrawable(R.drawable.selector_red)        .setImage(R.mipmap.ic_new_delete)        .setWidth(ViewGroup.LayoutParams.MATCH_PARENT)        .setHeight(ViewGroup.LayoutParams.MATCH_PARENT);
设置这样的高度肯定是不行的。
我的每个Item会因为文字的行数自动增加。

**Comment by s162738** [comment]
我决定用SwipeMenuLayout这个控件。感觉很好

**Comment by yanzhenjie** [comment]
嗯可以的，具体用法可以参考下Demo中的用SwipeMenuLayout实现自己的侧滑菜单。

**Comment by yanzhenjie** [comment]
现在框架原生已经支持菜单自适应高度了，你可以更新使用。介绍详情请看ReadMe。或者严振杰的博客：http://blog.csdn.net/yanzhenjie1003/article/details/52115566。
