### ISSUE TITLE
侧滑删除怎么会触发加载更多的接口？我怎么才能屏蔽

### ISSUE THREAD

**Issue by RookieHands** [yanzhenjie/SwipeRecyclerView#61]
侧滑删除怎么会触发加载更多的接口？我怎么才能屏蔽

**Comment by RookieHands** [comment]
当只有一页的时候

**Comment by BeforeFuture** [comment]
我也遇到了，把某一个item拉出来，点击删除，被删除的item上面的的某个item会跳出来一点，类似手动向左滑动了，等于触发了侧滑加载更多，但是显示的不太多，就出来一个标签的一部分

**Comment by yanzhenjie** [comment]
新版改了，优化了好多，看看新的介绍，感谢反馈。
