### ISSUE TITLE
SwipeMenuItem

### ISSUE THREAD

**Issue by woyoudianhuai** [yanzhenjie/SwipeRecyclerView#63]
SwipeMenuItem wechatItem = new SwipeMenuItem(mContext)
                        .setBackgroundDrawable(R.drawable.selector_purple)
                        .setImage(R.mipmap.ic_action_wechat)
                        .setText("微信")
                        .setWidth(width)
                        .setHeight(height);
SwipeMenuItem可否自由定制，怎么定制 还有就是文字和图片的位置定死了不爽

**Comment by yanzhenjie** [comment]
好吧，看来我需要再迭代一个版本了，用接口来实现，静待我的好消息吧！

**Comment by yanzhenjie** [comment]
忘记了，项目中有一个CardView演示的，那个不就是自定义菜单吗？可以放任何view的。
