### ISSUE TITLE
支不支持多种item间拖拽排序

### ISSUE THREAD

**Issue by sqq222** [yanzhenjie/SwipeRecyclerView#64]
RecyclerView 中不同类型的item 之间 拖拽 不能排序，不知道是不是我使用上有问题，相同的item间拖拽都是正常的，不同的拖拽无法排序

**Comment by yanzhenjie** [comment]
可以，需要自定义拖拽参数，请参考demo中的自定义拖拽flag的Activity，允许不同的ViewType之间拖拽即可！

**Comment by sqq222** [comment]
@yanzhenjie  参考了demo中的自定义拖拽flag的Activity 也不行呀，并发现只要重写getItemViewType，不同的viewType之间就排不了序。求大神再次指点

**Comment by yanzhenjie** [comment]
已支持。
