### ISSUE TITLE
jar包冲突导入后运行报这个错误很郁闷，找了包下面也没有这个类

### ISSUE THREAD

**Issue by MrRightDongYuJie1314** [yanzhenjie/SwipeRecyclerView#71]
Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: android/support/v4/database/DatabaseUtilsCompat.class

**Comment by yanzhenjie** [comment]
SwipeRecyclerView不支持Jar包，你的错看不出来和本库有关，可能是引用了不同版本的多个support库造成的。
