### ISSUE TITLE
开启左滑右滑的时候additem报错

### ISSUE THREAD

**Issue by Colaman0** [yanzhenjie/SwipeRecyclerView#75]
在oncreatemenu中addMenuItem的时候报错，错误是view已经有parent需要先removeview

**Comment by yanzhenjie** [comment]
这是因为开发者使用了自定了ViewHolder，新版1.1.1已经修复了这个问题。如果发现还有，请在用户目录，清除`.gradle`的缓存后重新`sync`项目即可。
