### ISSUE TITLE
The specified child already has a parent. You must call removeView() on the child's parent first

### ISSUE THREAD

**Issue by Yuphee** [yanzhenjie/SwipeRecyclerView#77]
页面一打开就报，无奈

**Comment by yanzhenjie** [comment]
这是因为开发者使用了自定了`ViewHolder`，新版1.1.1已经修复了这个问题。如果发现还有，请在用户目录，清除`.gradle`的缓存后重新`sync`项目即可。

**Comment by Destiny01** [comment]
连续点击刷新列表会把这个错误The specified child already has a parent. You must call removeView() on the child's parent first。
 at com.yanzhenjie.recyclerview.swipe.SwipeAdapterWrapper.onCreateViewHolder(SwipeAdapterWrapper.java:140)

**Comment by yanzhenjie** [comment]
麻烦把你连续执行刷新的代码贴一下，我再查一下。

**Comment by Destiny01** [comment]
解决了
