### ISSUE TITLE
第一次加载SwipeRefreshLayout页面效果和手动刷新效果不一致

### ISSUE THREAD

**Issue by chaozaiai** [yanzhenjie/SwipeRecyclerView#78]
第一次加载
![qq 20170801111855](https://user-images.githubusercontent.com/8943761/28807957-404a2e0a-76ab-11e7-9836-68cb1c53c27b.png)
 手动刷新
![qq 20170801111904](https://user-images.githubusercontent.com/8943761/28807964-47887cda-76ab-11e7-8330-fa385d5ab13c.png)

还请尽早回复一下。

**Comment by yanzhenjie** [comment]
如图，第一次加载时，显示了加载更多的`loading`，而这个`loading`如果没有调用过`recyclerView.loadFinish()`设置是不会显示的。这个方法应该在数据第一次成功加载后调用，告诉`SwipeRecyclerView`是否有更多数据，数据是否是空，这样`SwipeRecyclerView`才能决定是否要显示它。

**Comment by chaozaiai** [comment]
您这边说的是loadMoreFinish吗？我使用   recyclerView.useDefaultLoadMore()这个方法，默认的加载更多有一个loading,旁边还有一个文字说明。但是第一次加载只显示一个圈，你说这个是加载更多的loading感觉也有可能，但是为什么那个文字说明没有显示呢？我再看看

**Comment by chaozaiai** [comment]
谢谢严大大

**Comment by chaozaiai** [comment]
我这边在页面打开的时候，打了断点，没有执行loadMoreFinish方法，只有加载数据完成后才会去调用loadMoreFinish方法。如上面的图片，第一次加载下面会有一个图片，能确定是显示了foot的部分ui。代码如下：
```
//初始化recyclerview
swipeRefreshLayout.setOnRefreshListener(this);
recyclerViewDiscover.useDefaultLoadMore();
recyclerViewDiscover.setLoadMoreListener(this);
linearLayoutManager = new LinearLayoutManager(getContext());
discoverAdapter = new DiscoverAdapter(recyclerViewDiscover, articleListItems, R.layout.view_discover_item);
recyclerViewDiscover.setLayoutManager(linearLayoutManager);
recyclerViewDiscover.setAdapter(discoverAdapter);

//加载数据代码
 @Override
    public void renderDatas(List<ArticleListItem> articleListItems) {
        this.articleListItems = articleListItems;
        discoverAdapter.refresh(this.articleListItems);
        recyclerViewDiscover.loadMoreFinish(false, true);
    }

    @Override
    public void loadMoreDatas(List<ArticleListItem> articleListItems) {
        this.articleListItems.addAll(articleListItems);
        discoverAdapter.notifyDataSetChanged();
        recyclerViewDiscover.loadMoreFinish(false, true);
    }

    @Override
    public void isRefreshing(boolean isRefresh) {
        swipeRefreshLayout.setRefreshing(isRefresh);
    }

    @Override
    public void onRefresh() {
        presenter.loadArticle();
    }

    @Override
    public void onLoadMore() {
        presenter.loadMoreArticle();
    }

    @Override
    public void noMoreData() {
        recyclerViewDiscover.loadMoreFinish(false, false);
    }
```

**Comment by chaozaiai** [comment]
我看了最新版本的1.1.1，您应该修复了那个第一次加载数据，显示加载更多的动画。但是应该只是修改了不显示那个pregressbar，如果给item加分割线的话，分割线还是会显示的。

**Comment by yanzhenjie** [comment]
嗯，之前好像是有visiable没设置到，忘记给你回复了。
item分割线的话，这个暂时没有办法，Footer会占有一个Item的，其实用户看到最下面是最后一个Item和分割线和一个白色区域，这个应该可以忽略。
如果你的效果我描述不一致，你把图贴上来一下，我再看看。

**Comment by chaozaiai** [comment]
对的，现在是footer的加载动画不显示了，但是最后item的分割线还是会有的。如下图：
![image](https://user-images.githubusercontent.com/8943761/29166906-d828d950-7dfa-11e7-9f62-cbf12d41ee95.png)
所以在想，怎么才能第一次加载，也就是adapter没有item数据的时候，footer不显示呢？

**Comment by yanzhenjie** [comment]
![qq 20170811111751](https://user-images.githubusercontent.com/13534988/29200338-157952e4-7e87-11e7-8d24-383cdafab34b.png)
这里有两个重载的构造方法，使用第二个即可。
第一个参数是颜色，第二个参数是分割线的size（单位px），第三个参数是哪个ViewType不需要画分割线，第三个参数填`2000 + recyclerView.getFooterItemCount()`即可解决这个问题。

**Comment by chaozaiai** [comment]
谢谢严大大。我用的是自己的分割线类，我试试先。

**Comment by yanzhenjie** [comment]
刚刚更新了哭，增加了一个DefaultDecoration类，不会为LoadMoreView加分割线，同时支持Grid和Linear形式，看看ReadMe的介绍。
