### ISSUE TITLE
能不能关闭某一行item的侧滑，只让指定item可以侧滑，提供的有方法么

### ISSUE THREAD

**Issue by lygttpod** [yanzhenjie/SwipeRecyclerView#79]

**Comment by yanzhenjie** [comment]
请参考自定义拖拽参数的`Activity`。

**Comment by Doraemonhub** [comment]
swipeMenu.setOnItemMovementListener(mOnItemMovementListener);RecyclerView在setonItemMovementListener之后无效，debug也进不到 mOnItemMovementListener中 是什么原因呢？

**Comment by smartsean** [comment]
我也是设置无效。咋整啊，。。。
