### ISSUE TITLE
关于CardView事件冲突

### ISSUE THREAD

**Issue by 724191861** [yanzhenjie/SwipeRecyclerView#83]
作者你好！
我在你的Demo里发现，当Item时CardView的时候（特殊），整个item无法响应点击事件；还有点击侧滑出来的view也无法响应。这个该怎么解决呢？

**Comment by yanzhenjie** [comment]
今天更新了库，增加了DefaultDecoration默认分割线，供开发者选择使用。
同时更新了Demo，看看Demo中的CardView的处理。
