### ISSUE TITLE
设置OnItemStateChangedListener闪退

### ISSUE THREAD

**Issue by Alpha-chen** [yanzhenjie/SwipeRecyclerView#84]
java.lang.NullPointerException: Attempt to invoke virtual method 'void com.yanzhenjie.recyclerview.swipe.touch.DefaultItemTouchHelper.setOnItemStateChangedListener(com.yanzhenjie.recyclerview.swipe.touch.OnItemStateChangedListener)' on a null object reference
                                                                            at com.yanzhenjie.recyclerview.swipe.SwipeMenuRecyclerView.setOnItemStateChangedListener(SwipeMenuRecyclerView.java:124)

**Comment by yanzhenjie** [comment]
用的哪个版本？升级到最新版本应该就没问题了，如果不方便升级，可以先调用`isLongPressDragEnabled()`或者`setLongPressDragEnabled()`方法后再调用`setOnItemStateChangedListener()`。

**Comment by Alpha-chen** [comment]
忘记是哪一个版本了，我是直接源码引入的。 我这里采用
` /**
     * Set OnItemStateChangedListener.
     *
     * @param onItemStateChangedListener {@link OnItemStateChangedListener}.
     */
    public void setOnItemStateChangedListener(OnItemStateChangedListener onItemStateChangedListener) {
        initializeItemTouchHelper();// 在注册监听的时候，重新初始化一次helper
        this.mDefaultItemTouchHelper.setOnItemStateChangedListener(onItemStateChangedListener);
    }
`

**Comment by yanzhenjie** [comment]
对，源码的话加这个就好了，但是建议你使用最新版，你可以看看新的介绍。

**Comment by Alpha-chen** [comment]
最新版代码更加简洁了，很多代码都抽象到父类里面了，扩展性更好了。
很赞，尽快迁移到最新版。

**Comment by Alpha-chen** [comment]
另外，在SwipeMenuLayout滑动的时候，最好可以回调出来一个接口，
实时的回调给上层，上层可以根据滑动的回调，对item内部的view 做动画操作。
//----------------------------------------------------------------------------------
我自己实现了一个接口，监听到开始滑动状态，结束的状态。虽然也满足简单的状态点的回调。
但状态不是连续，上层item在做内部动画的时候就会很生硬。
//----------------------------------------------------------------------------------
不是很美滋滋

**Comment by yanzhenjie** [comment]
明白我尽快添加一个方法。
