### ISSUE TITLE
请问这个SwipeMenuRecyclerView有什么方法禁止侧滑吗？

### ISSUE THREAD

**Issue by l1239155492** [yanzhenjie/SwipeRecyclerView#86]
请问这个SwipeMenuRecyclerView有什么方法禁止侧滑吗？

现在我们的需求是处于编辑模式，禁止侧滑。

**Comment by whoAllen** [comment]
不掉用侧滑方法就可以吧。
而且你可以根据返回的不同的type来决定要不要侧滑

**Comment by yanzhenjie** [comment]
@whoAllen 同学说的是对的。
另外，如果你已经启用了侧滑，那么还是调用那个方法，传入false即可立刻禁止侧滑功能。
