### ISSUE TITLE
RecycleView 自动显示在屏幕中间

### ISSUE THREAD

**Issue by shenxiaolin** [yanzhenjie/SwipeRecyclerView#9]
这个recycleView 是否可以UI 中任意一个可见的Item 支持点击之后，自动滚动到屏幕中间呢，

**Comment by yanzhenjie** [comment]
你的意思是这个Item到屏幕中间吗？理论上是可以的，但是我还这么做过。这个要从RecyclerView入手，不属于框架层级的。你可以Google搜索看下，不过RecyclerView的某几个Item是肯定不能滚动到屏幕中间的，因为他们在最顶部或者最底部。

**Comment by shenxiaolin** [comment]
明白你的意思，最顶部+最底部；
我这种需求的case 是基于前面和后面都还有元素的情况下；
